### ISSUE TITLE
register signals here

### ISSUE THREAD

**Issue by baseplate-admin** [KrystianMaccs/cinema#2]
https://github.com/KrystianMaccs/cinema/blob/f15d5deadc499f4e799ed565c58669d6b9870e23/apps/ratings/apps.py

**Comment by KrystianMaccs** [comment]
Oh sorry, I forgot to mention that I changed the repo to this:
https://github.com/KrystianMaccs/Movies.git Had db issues that I couldn't
resolve and I was running out of time.
